38 display live data (Domain)
Semester3-03/Java-application pull request #115
Opened 2020-11-20 14:21 UTC by Wylardt

Co-authored-by: Christopher Kas <christopher@kas.net>

close #38 
close #113 
close #111 
close #114

2020-11-20 14:32 UTC, Lise4070 approved these changes

2020-11-20 20:02 UTC, Lawst96 requested changes

2020-11-26 22:08 UTC, Kaszz commented
After recent changes it is likely that everything but "read methods for each ingredient (Domain) #113" is unnecessary

2020-11-27 08:20 UTC, dottore1 approved these changes

2020-11-27 08:21 UTC, Lawst96 approved these changes

2020-11-27 12:59 UTC, Teyson approved these changes

2020-11-27 15:21 UTC, closed without merging