Implement Batch
Semester3-03/Java-application pull request #78
Opened 2020-11-06 12:02 UTC by Lise4070

2020-11-06 12:11 UTC, dottore1 approved these changes

2020-11-06 12:19 UTC, Lise4070 commented on src/main/java/com/BrewMES/demo/model/Batch.java
> +			for (int i = 0; i < 18; i++) {
Er det 18 eller 19 states?

2020-11-06 13:09 UTC, Teyson requested changes

2020-11-06 13:09 UTC, Teyson commented on src/main/java/com/BrewMES/demo/model/Batch.java
> +			for (int i = 0; i < 19; i++) {
Der er faktisk 20 states xD
Vi skal bare lige have testet om vi rent faktisk bruger dem alle, og der skal så vurderes om vi stadig vil tracke de states der ikke bliver brugt, hvis de ikke bliver brugt.
Min tanke er at de bare skal trackes, idet det vil gøre det MEGET nemmere :)

2020-11-06 13:09 UTC, Teyson commented on src/main/java/com/BrewMES/demo/model/Machine.java
> +                    case STOP  -> connection.writeValue(cntrlCmd, DataValue.valueOnly(new Variant(3))).get();
TAK! Min OCD var ved at rive mig helt i stykker xD

2020-11-06 13:11 UTC, Lise4070 commented on src/main/java/com/BrewMES/demo/model/Machine.java
> +                    case STOP  -> connection.writeValue(cntrlCmd, DataValue.valueOnly(new Variant(3))).get();
Same

2020-11-10 13:51 UTC, Kaszz commented on src/main/java/com/BrewMES/demo/model/Batch.java
> +			for (int i = 0; i < 19; i++) {
Der er faktisk 17 states (0-11) (15-19). Resten af din kommentar er jeg enig med.

2020-11-12 14:12 UTC, Wylardt approved these changes

2020-11-16 11:32 UTC, Lise4070 commented on src/main/java/com/BrewMES/demo/model/Batch.java
> +			for (int i = 0; i < 19; i++) {
Sandt. Det er ændret.

2020-11-16 15:35 UTC, Kaszz approved these changes
Overvej om det skal være et map istedet for en arraylist så vi kan benytte pladserne 0-11 og 15-19. Jeg approver dog stadig, da jeg antager det her ville virke fint 🐸

2020-11-20 12:27 UTC, dottore1 approved these changes

2020-11-20 12:29 UTC, Wylardt approved these changes

2020-11-20 12:37 UTC, Lawst96 requested changes

2020-11-20 12:37 UTC, Lawst96 commented on src/main/java/com/brewmes/demo/BrewMesApplication.java
> +
Revert this, it breaks the file.

2020-11-20 14:05 UTC, Kaszz approved these changes
🐸

2020-11-20 14:05 UTC, Lawst96 approved these changes

2020-11-20 14:06 UTC, Teyson approved these changes

2020-11-20 14:07 UTC, merged